language: php
php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=sqlite

branches:
  only:
    - master

before_install:
  - tests/travis/before_install_$DB.sh
  - tests/travis/before_install.sh
  - cp tests/core_install.sh ../core/

install:
  - cd ../core
  - ./core_install.sh $DB

script:
  # Test lint
  - cd ../core/apps/activity
  - sh -c "if [ '$DB' = 'sqlite' ]; then ant test; fi"

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: DB=oracle
  allow_failures:
    - php: hhvm
  fast_finish: true
